// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RedirectionchoosecarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void redirectionchoosecar() {
    driver.get("https://www.booking.com");
    driver.findElement(By.linkText("Аренда машин")).click();
    driver.findElement(By.id("ss_origin")).click();
    driver.findElement(By.id("ss_origin")).sendKeys("Санкт");
    WebDriverWait wait1 = new WebDriverWait(driver, 10);
    wait1.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".sb-autocomplete__item-with_photo:nth-child(1) > span:nth-child(2)")));
    driver.findElement(By.cssSelector(".sb-autocomplete__item-with_photo:nth-child(1) > span:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".sb-searchbox__button > span:nth-child(1)")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ab-SearchSummary_PickUp_City")));
    }
    assertThat(driver.findElement(By.cssSelector(".ab-SearchSummary_PickUp_City")).getText(), is("Санкт-Петербург"));
  }
}
